channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.0.1
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - feature-engine==1.9.3
  - numpy==2.3.2
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==21.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
